spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/rent
    username: root
    password: root
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Inventory-service